### ISSUE TITLE
[proposal] Project useless files cleanup

### ISSUE THREAD

**Issue by asskey** [HassanKanj/LazyKit#1]
when i finish a project i end up with useless files (images,css,js anything) that are not used anywhere and are not pointed at. It would be nice to have something to scan my code and my files and then tells me which files i can safely delete.

**Comment by HassanKanj** [comment]
That's a good idea, I will work on a command that will scan all the files in a directory and list the ones that can be safely deleted, and maybe as a next step, I will modify the code to delete the files but it should copy them first to a backup folder (just in case something went wrong).

**Comment by HassanKanj** [comment]
I have created the command, it is called utility:detectUselessFiles
Documentation: https://github.com/HassanKanj/LazyKit/wiki/Detect-useless-files
